### ISSUE TITLE
Failed to register everything from references.csv

### ISSUE THREAD

**Issue by timabell** [timabell/msaccess-vcs-integration#1]
Error on import:
	---------------------------
	Microsoft Access
	---------------------------
	Failed to register {000204EF-0000-0000-C000-000000000046}
	---------------------------
	OK   
	---------------------------

references.csv:

	{000204EF-0000-0000-C000-000000000046},4,2
	{4AFFC9A0-5F99-101B-AF4E-00AA003F0F07},9,0
	{00020430-0000-0000-C000-000000000046},2,0
	{4AC9E1DA-5BAD-4AC7-86E3-24F4CDCECA28},12,0
	{B691E011-1797-432E-907A-4D8C69339129},6,1
	{00020813-0000-0000-C000-000000000046},1,8
	{420B2830-E718-11CF-893D-00A0C9054228},1,0
	{00020905-0000-0000-C000-000000000046},8,6
	,0,0

Message repeated for about half of the refs, couldn't get any to load by elimination

Seems to have loaded them anyway so may be a red herring.

**Comment by jwbrookes** [comment]
Your getting this error because the ref is already present in the project. Access adds a number of references to a project by default. For example the first reference will be for the VBA library (your code won't get very far without that!).

These duplicate ref errors should really be dropped silently, as they don't affect the project.

**Comment by timabell** [comment]
oh! that makes sense now, didn't think of that
